package:
   name: intake-mongo
   version: 0.0.1

source:
   path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - intake
    - mongoadapter
    - pymongo
    - mongo-driver

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_mongo tests

about:
  home: https://github.com/ContinuumIO/intake-mongo
  license: BSD
  license_file: LICENSE
  summary: |
    MongoDB plugin for Intake
